### ISSUE TITLE
Weapon Customization Details

### ISSUE THREAD

**Issue by NateAGeek** [NateAGeek/Unconventional-Weapons-Vs.-The-World#4]
Make a Entity that is the Weapons. Still need to figure out what the type of items/trash are to build  these weapons, weapon durability, ammo.

Mini:
- Scraps that are around that can be used to make temporary weapons, not really that strong

Major:
- Need to be at a work bench to build a big weapon

Weapon Types:
- Melee (Stick -> Based on what is in the stick, will do more damage and stuff)
- Projectile Based (Grip, Stock, Barrel, Mag)
- Traps (Kinda don't know the component)

**Comment by HotelCalifornia** [comment]
Weapon durability

**Comment by HotelCalifornia** [comment]
Also ammo
